### ISSUE TITLE
Choose project name

### ISSUE THREAD

**Issue by brylie** [api-standards/governance#2]
We can use a project name for varios purposes such as social media, domain name registration, and possibly incorporating as an independent non-profit. 

# Task
* [ ] Discuss name ideas
* [ ] Discuss existing organizations with overlapping scope
* [ ] Determine if name change is needed
* [ ] Determine whether 'working-group' status is sufficient moving forward

**Comment by ahmadnassri** [comment]
inspiration: http://todogroup.org/

**Comment by brylie** [comment]
IMHO, *API Umbrella* seems like a good working group name! @GUI thoughts?

**Comment by ahmadnassri** [comment]
following the w3c group namings: `API Standards Working Group` seems a bit more appropriate.

*API Umbrella* is already recognized as a product, name, wouldn't be confusing to the community, better have a descriptive name.

**Comment by brylie** [comment]
Alright, lets consider the name proposal: API Standards Working Group (APISwg for short).
