### ISSUE TITLE
Create mission statement

### ISSUE THREAD

**Issue by brylie** [api-standards/governance#3]
As a working group, we can benefit from a succinct mission statement. This will help us prioritise our efforts and determine what actions to take within the working group scope.

# Task
* [ ] Discuss relevant working group tasks
* [ ] Make a list of working groups goals/objectives
* [ ] Refine goals and objectives into single paragraph
* [ ] Refine goals and objectives paragraph into a mission statement
* [ ] Add the mission statement to the Github organization description, social media account(s), etc.

**Comment by ahmadnassri** [comment]
I would say this should be the top priority.
